language: ruby
rvm:
  - 2.1.4

services:
  - redis-server

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/application.example.yml config/application.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:schema:load
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
